name: AstroMan Marketing Agent

on:
  schedule:
    - cron: "0 8 * * *"    # 12:00 Georgia time
    - cron: "0 16 * * *"   # 20:00 Georgia time
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: node generate.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
